// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2HsmSH_t4thLUUpHFj-l2vQMBc_eTDw4',
    appId: '1:471380279403:web:117ad094d60a55fb5ff12e',
    messagingSenderId: '471380279403',
    projectId: 'cloud-photo-cd688',
    authDomain: 'cloud-photo-cd688.firebaseapp.com',
    storageBucket: 'cloud-photo-cd688.appspot.com',
    measurementId: 'G-ZJ1Y68YECB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoIim0yKwokrQvElIb03fT9tcy0Z4sZjE',
    appId: '1:471380279403:android:e8533b2cad92168d5ff12e',
    messagingSenderId: '471380279403',
    projectId: 'cloud-photo-cd688',
    storageBucket: 'cloud-photo-cd688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcpmOctVXjUv-A_3R63MtCl_1wnAhzYdA',
    appId: '1:471380279403:ios:e34b8f502c7e99685ff12e',
    messagingSenderId: '471380279403',
    projectId: 'cloud-photo-cd688',
    storageBucket: 'cloud-photo-cd688.appspot.com',
    iosBundleId: 'com.example.testingblocCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcpmOctVXjUv-A_3R63MtCl_1wnAhzYdA',
    appId: '1:471380279403:ios:e34b8f502c7e99685ff12e',
    messagingSenderId: '471380279403',
    projectId: 'cloud-photo-cd688',
    storageBucket: 'cloud-photo-cd688.appspot.com',
    iosBundleId: 'com.example.testingblocCourse',
  );
}
